### ISSUE TITLE
Long file name.

### ISSUE THREAD

**Issue by rusk911** [brummer10/neural-amp-modeler-ui#1]
Is it possible to crop long file names an display full name in tooltips?
![Screenshot at 2024-01-31 10-04-01](https://github.com/brummer10/neural-amp-modeler-ui/assets/7164744/faee434d-f5aa-49d6-9fe8-b619ef88fc14)

**Comment by brummer10** [comment]
Hi
Yes, I've pushed a fix for it to the repository now. long file names will be coped now and the tooltip will appear on the file browser button.

**Comment by rusk911** [comment]
> Hi Yes, I've pushed a fix for it to the repository now. long file names will be coped now and the tooltip will appear on the file browser button.

strange. pulled changes, rebuilt and reinstalled but see no changes in gui

**Comment by brummer10** [comment]
That's really strange. Is that a Hdpi monitor?

**Comment by rusk911** [comment]
No. 1680x1050 old LCD.

**Comment by rusk911** [comment]
Now it looks better, but still not ideal
![Screenshot at 2024-01-31 14-51-43](https://github.com/brummer10/neural-amp-modeler-ui/assets/7164744/3e2c0893-bbe7-4e06-bbce-584d450cd389)

**Comment by brummer10** [comment]
Which set is that? Seems I need to check that one to find out what goes wrong here.
All sets I tested so far crop correctly. My impression is that "numbers" wouldn't be correctly handled by my crop function.

**Comment by rusk911** [comment]
Most NAM model files I downloaded contains some hash and capture parameters. For example this: 2555SL-P6.5-B5-M6-T6.5-OM6-LM7-G7-GE7-c4111ae17efbd50382b3b7abfdfc004c.nam

**Comment by brummer10** [comment]
Yep. I see now. I'll investigate. 
Thanks for the hint.

**Comment by brummer10** [comment]
Okay, got it. There was a error in my calculation.
Should be fixed now really.  (Fingers cross :) )

**Comment by rusk911** [comment]
Yes. Much better now. Last 2 dots still are out of frame but it's not a big issue. I still have some notice about usability, but I guess it's not for this repository. Every time I open file browser I have to switch to list view. Non-ui version opened last used setting. Same for all system dialogs (Linux Mint). First time I navigate to NAM files location it shows subfolders, next time I open a file browser it shows only NAM files with no subfolders. I beleave better delegate this function to system-wide file dialogue or host used, but not implement own file browser. 
![Screenshot at 2024-01-31 15-30-34](https://github.com/brummer10/neural-amp-modeler-ui/assets/7164744/c0a17043-6096-4f8c-aeea-d1a11c9cff53)

**Comment by rusk911** [comment]
> the file browser don't show subfolders is a bug. I've fixed that now.

Still not fixed. After loading a nam file from a folder with mixed subfolders and nam files it still shows only files, but no subfolders. I have to navigate again to the location to see them.
![Screenshot at 2024-02-01 10-58-51](https://github.com/brummer10/neural-amp-modeler-ui/assets/7164744/a32276d1-37a3-4047-bfca-a820de5b728d)

**Comment by rusk911** [comment]
Oh, sorry, my bad. I forgot to update submodules. Confirm, subfolders issue is fixed. Thank you! Great job!

**Comment by brummer10** [comment]
When you now do a pull again (including submodule update) you'll get the "store the list view and size" as well. True, we could only store the state during session, but I guess that's already helps. 
I've as well reworked the crop function a bit, hopefully it will crop the filename now so that it fit completely into the space.

Thanks for your suggestions.

**Comment by rusk911** [comment]
Yes, great. Everything is working now. Thank you!
